### ISSUE TITLE
Support ember-modifier v4

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-popper-modifier#570]
ember-popper-modifier should support `ember-modifier@^4` in parallel to version 3 to allow applications (and other addons depending on it) to upgrade to Ember Modifier v4 themselves. This issue lists the remaining tasks to do so.

- [ ] Refactor ember-modifier to use `modify` hook available since `ember-modifier@>=3.2.0` (#452 and #508)
- [ ] Drop support for node < 14 (#577)
- [ ] Drop support for Ember < 3.24 (#578)
- [ ] Widen version range for `ember-modifier` to `^3.2.0 || ^4.0.0`

**Comment by jelhan** [comment]
Support has been shipped in [v3.0.0](https://github.com/adopted-ember-addons/ember-popper-modifier/releases/tag/v3.0.0).
